= Registration Parameters

The available configuration parameters for Registration are the
following:

* `rps`
+
Type: float
+
Default value: _``1.0``_
+
Registration per second, that is the number of registrations sent out by
the traffic case. When the `rps` is set to _``0.0``_, the registration does not
start until a greater value is set.
+
For example, when 10000 entities are defined in the traffic case and 100
entities register per second (`rps` := _``100.0``_), then it takes 100 seconds
for all 10000 entities to register.
+
Unit: 1/sec

* `tempId`
+
Type: boolean
+
Default value: _``false``_
+
When set to _``true``_, the simulated users use a temporary identifier at
registration. This ID is replaced later with the associated URI received
in the [maroon]#200 OK#.
+
The `usedPAssocURIElement` parameter defines which associated URI element
is used further. The first element is used when the `usedPAssocURIElement`
is greater than the number of associated URI.

* `usedPAssocURIElement`
+
Type: integer
+
Default value: _``1``_
+
Defines which associated URI element is used. This parameter is used
when `tempId` parameter is set to _``true``_.

* `registrationExpires`
+
Type: float
+
Default value: _``3600.0``_, based on link:http://www.ietf.org/rfc/rfc3261.txt[RFC
3261]
+
The registration of entities in the IMS system expires after a certain
time. The expiration time is sent to the IMS system in the [header]#Expires#
header of the [message]#REGISTER# message. Upon registering, the entity sends the
initial value set in the `registrationExpires` parameter to the IMS
system. The real expiration time is the value included in the [maroon]#200 OK#
response of the registration sent by the IMS system.
+
Unit: sec

* `sbgRegMinExpires`
+
Type: float
+
Default value: _``0.0``_
+
When its value is greater than _``0.0``_, it is used to control that no
re-registrations are sent earlier than this time ahead of expiry. When
set to _``0.0``_, the re-registration occurs at a percentage of the total
expiration time (95% by default).
+
Unit: sec
+
> ==== Note::Note 
> 
> It is in effect only if the `distributeRegister` value is _``true``_.

* `reRegMargin`
+
Type: float
+
Default value: _``10.0``_
+
When its value is greater than or equal to _``0.0``_, it specifies the time of
re-registration ahead of expiration. When
link:../../HTTPRest_over_WebSocket.xml[WebSocket] is used and
`reRegMargin` is set to _``0.0``_, the re-registration occurs at a percentage of
the total expiration time (95% by default).  
+
Unit: sec

* `reRegistration`
+
Type: boolean
+
Default value: _``true``_
+
Allows or permits the entities of the Traffic Case to re-register (that
is to send [maroon]#re-REGISTER# messages).
+
Unit: 1/sec
+
The registration of entities on the IMS network expires after a certain
time. For more information, see parameter `registrationExpires` above.
When this time elapses, the entities cannot request services from IMS
until they re-register.
+
To avoid this de-registration, the entities re-register to IMS
regularly.

* `maxRetryAfter`
+
Type: integer
+
Default value: _``3``_
+
The number of occasions when an entity can try to repeat sending its
registration request, after receiving an unsuccessful response that
includes a [maroon]#_Retry-After_# header with the suggested waiting time until the
next try. It sets the maximum number of consecutive responses received
including a [maroon]#_Retry-After_# header before a call is marked as failed.

* `retryAfterFail`
+
Type: float
+
Default value: _``30.0``_
+
The number of seconds that should be waited before trying to register
again the first time after an error, when there is a [maroon]#_Retry-After_# field
in the unsuccessful response used for the first time.
+

SNIPPET HERE: regWatchdog.hts

* `PAccessNetworkInfo`
+
Type: charstring
+
Default value: _``empty string``_
+
Used to set the content of the [maroon]#_P-Access-Network-Info_# header of [maroon]#REGISTER#
messages. If the default value is used or the parameter is omitted, no
[maroon]#_P-Access-Network-Info_# header is added to the messages at all.
+
Allowed values:

** _``undefined``_
** _``IEEE-802.11``_
** _``IEEE-802.11a``_
** _``IEEE-802.11b``_
** _``IEEE-802.11g``_
** _``3GPP-GERAN``_
** _``3GPP-UTRAN-FDD``_
** _``3GPP-UTRAN-TDD``_
** _``ADSL``_
** _``ADSL2``_
** _``ADSL2+``_
** _``RADSL``_
** _``SDSL``_
** _``HDSL``_
** _``HDSL2``_
** _``G.SHDSL2``_
** _``VDSL``_
** _``IDSL``_
** _``3GPP2-1X``_
** _``3GPP2-1X-HRPD``_
** _``DOCSIS``_

* `includeTransportInContact`
+
Type: boolean
+
Default value: _``false``_
+
When set to _``true``_ or _``omitted``_, the [maroon]#_Contact_# header of the [maroon]#REGISTER# messages
contains the transport protocol (for example Contact:
<…transport=udp…>). When set to _``false``_, the transport protocol is not
included in the [maroon]#_Contact_# header.
+
* `distributeRegister`
+
Type: boolean
+
Default value: _``false``_
+
When set to _``true``_, the registers are distributed, if possible, over the
expiration time. If the `sbgRegMinExpires` is set to value > _``0.0``_, the
first required expiration time is: 
+
`expires = <user-index> * 1.618 + sbgRegMinExpires`
+
When `sbgRegMinExpires` is set to _``0.0``_, the first
required expiration time is: 
+
`expires = <user-index> *  1.618 + <registrationExpires>`
+
For all value modulo, `360000.0` is calculated.

* `delayInitialRegister`
+
Type: float
+
Default value: _``0.0``_
+
The initial register is delayed with the time specified in this
parameter. The normal use case for this is parallel ringing, where the
same subscriber registers from different locations. Since multiple
simultaneous registers are not allowed for one user, it is required to
put a delay on the register for the second, third, etc. scenario, where
the same subscribers should register in.

* `authHeaderInInitialReg`
+
Type: boolean
+
Default value: _``false``_
+
When set to true, the [maroon]#_Authorization_# header is included in the initial
and the [maroon]#de-REGISTER# messages.

> ==== Note::Note
> 
> When AKA authentication is set, the [maroon]#_Authorization_# header is always included in the initial and in the [maroon]#de-REGISTER# messages, independently of this parameter.

* `deregisterCurrentContactOnly`
+
Type: boolean
+
Default value: _``false``_
+
When set to _``true``_, only the current contact for the given user is
de-registered, that is, only the contact address is inserted into the
Contact header of the [maroon]#de-REGISTER# message (instead of all of them using
the * syntax in the [maroon]#_Contact header_#, which is the case if the parameter
is set to _``false``_ or is omitted).

* `enableSTUN`
+
Type: boolean
+
Default value: _``false``_
+
When set to _``true``_, STUN binding requests are sent in every `keepAliveSTUN`
seconds.

* `keepAliveSTUN`
+
Type: float
+
Default value: _``30.0``_
+
When `enableSTUN` is true, this is the timer that specifies how often the
STUN binding requests are sent.

* `keep`
+
Type: IMS_TC_Registration_keep
+
Enables the inclusion of keep parameter to [maroon]#_Via_# header, and defines the
frequency of [maroon]#REGISTER# messages that contains keep.
+
** `enable`
+
Type: boolean
+
Default value: _``false``_

** `frequency`
+
Type: integer
+
Default value: _``1``_

* `halfcall`
+
Type: boolean
+
Default value: _``false``_
+
When the `halfcall` parameter of a Traffic Case is set to _``true``_, the
Loadgen phase is started right after the first successful registration
(it does not wait for all entities to be registered).
+
When set to _``false``_, the Loadgen phase starts only after all entities are
registered. For more information, see
link:../../Phases_of_Execution.xml[Phases of Execution].

* `ignore`
+
Type: EPTF_IntegerList
+
Default value: _``empty integer list``_
+
Defines a list of 3xx-6xx SIP response codes that are not to be dealt
with. If `ignored` response is received, there is no affect on the verdict
of the call flow. The parameter contains the list of changing integers.

** IMS_TC_Registration_retryLogicParams

* `retryLogicParams`
+
Type: IMS_TC_Registration_retryLogicParams
+
Register retry logic implements a much more refined registration method.
It makes it possible to use the proxyList to change the actual proxy
when no response is sent. When there is a response, but it is an error
message, a special method determines when registering should be tried
again. This parameter contains the settings of the calculation method.
Its subparameters are the following:

** `maxTime`
+
Type: float
+
Default value: _``1800.0``_
+
Optional parameter. It is the maximum time for the next retry attempt.
It is used in a formula to calculate available seconds for the next
retry attempt.
+
Unit: sec

** `baseTime`
+
Type: float
+
Default value: _``30.0``_
+
Optional parameter. It is the base time for the next retry attempt. It
is used in a formula to calculate available seconds for the next retry
attempt.
+
Unit: sec

* `reRegType`
+
Type: IMS_Configuration_Registration_reRegType
+
Default value: _``DEFAULT``_ (the Call-ID remains the same)
+
The `reRegType` parameter defines whether the Call-ID in the [maroon]#re-REGISTER#
messages remains, or the application generates new ones for every
[maroon]#re-REGISTER# message. Its value can also be _``INITIAL``_ (new Call-IDs is
generated).

* `reRegRPS`
+
Type: float
+
Default value: _``omit``_
+
Number of re-registrations sent out by the traffic case in each and
every second. When it is set, the re-registration is not based on the
calculated expiration time any more but the entities re-register with
this rate.
+
Unit: 1/s
+

> ==== Note::This parameter can be modified on the GUI only if it is present in the configuration file. 
> 
> This parameter is called Target CPS on the GUI
and can be found on Execution Control panel > Statistics tab then Select
Entity Group > Select Scenario and choose the reRegistration traffic
case.

* `waitForDeReg`
+
Type: float
+
Default value: _``omit``_
+
Time (in seconds) to wait until an entity de-registers. The entities
de-register when this time elapses.
+
When running registration traffic case, it is possible to specify the
exact time of being registered in the IMS system for the entities.
Through the setting of the `waitForDeReg` parameter, the user can define
the amount of time spent in registered state. After the registration is
successful and the `waitForDeReg` time expired, the entity de-registers.

* `oauth`
+
Type: IMS_TC_Registration_oauth
+
Default value: _``omit``_
+
Describes the elements of `OAuth` field.
+
There is an [maroon]#_Authorization_# header in a [maroon]#REGISTER# message, if it is the
reply to a [maroon]#401 – Unauthorized response#, or if `authHeaderInInitialReg`
parameter is enabled. The `OAuth` field is a record in the [maroon]#_Authorization_#
header with the following structure:
+
Example:
+
[source]
----
oauth := {
    httpCode := 200,
    serviceProviderIdLow := 1,
    serviceProviderIdHigh := 5
}
----
+
All values in `OAuth` field must be positive integers, `httpCode` having
exactly three digits,
while `serviceProviderIdLow` and `serviceProviderIdHigh` having one or two
digits.
+
If the `oauth` parameter is set, the `OAuth` field is included in the
[maroon]#_Authorization_# header of the [maroon]#REGISTER# messages. The `oauth` parameter is
a string containing three elements: `httpCode` + `service provider id` +
`expiration time`. If both `serviceProviderIdLow` and
`serviceProviderIdHigh` are missing, the default values are used. If
only the `serviceProviderIdLow` or the `serviceProviderIdHigh` is missing,
the existing one is used instead of the missing one.
+
An example for this parameter in an outgoing [maroon]#REGISTER# message can be the
following:
+
`oauth="200013600"`
+
The first three digits are the `httpCode`, the next two digits are a
`service provider id` evenly distributed in the given range, while the
rest of the string is the `expiration time`.

* `addUserAgentHeaderDontChallenge`
+
Type: boolean
+
Default value: _``false``_
+
When set to _``true``_, after a [maroon]#401# response, all [maroon]#REGISTER# messages contain a
[maroon]#_UserAgent_# header with the value _``dont_challenge``_.

* `isDuaClient`
+
Type: boolean
+
Default value: _``false``_
+
Optional parameter. When set to _``true``_, DUA Client is enabled.

* `enableFailover`
+
Type: boolean
+
Default value: _``true``_
+
Enables proxy failover feature for registration.

* `changeNetworkAccess`
+
Type: changeNetworkAccessType
+
Default value: _``omit``_
+
Enables user access change from WiFi to LTE and vice versa. Its
subparameters are the following:

** `originalNetwork`
+
Type: enumerate
+
It has two elements, LTE_E(0) and WIFI_E(1). It indicates the original
network type. It is included in init Register and deRegister.

** `waitBeforeReReg`
+
Type: float
+
Default value: _``5.0``_
+
It indicates the time before sending `reRegistration` in order to change
network access. After the call is finished, two more registrations are
sent. The first to the opposite of the original network, the other to
the original network.
+
Unit: sec

** `waitBeforeUpdate`
Type: float
+
Default value: _``omit``_ (no UPDATE message is sent)
+
It indicates the time delay when sending [maroon]#UPDATE# message after the call
is established. This parameter is applicable only for
link:../CallTerm.xml[CallTerm] traffic case. It has no effect on other
traffic cases.

[[Table]]
= Table

[options="header",cols="verse*5"]
|===
|Command-Name	|Source node	|Destination node	|Abbreviation	|Code
|Update-Location-Request	|MME	|HSS	|ULR	|316
|Update-Location-Answer	|HSS	|MME	|ULA	|316
|Cancel-Location-Request	|HSS	|MME	|CLR	|317
|Cancel-Location-Answer	|MME	|HSS	|CLA	|317
|Authentication-Information-Request	|MME	|HSS	|AIR	|318
|Authentication-Information-Answer	|HSS	|MME	|AIA	|318
|Insert-Subscriber-Data-Request	|HSS	|MME	|IDR	|319
|Insert-Subscriber-Data-Answer	|MME	|HSS	|IDA	|319
|Delete-Subscriber-Data-Request	|HSS	|MME	|DSR	|320
|Delete-Subscriber-Data-Answer	|MME	|HSS	|DSA	|320
|Purge-UE-Request	|MME	|HSS	|PUR	|321
|Purge-UE-Answer	|HSS	|MME	|PUA	|321
|Reset-Request	|HSS	|MME	|RSR	|322
|Reset-Answer	|MME	|HSS	|RSA	|322
|Notify-Request	|MME	|HSS	|NOR	|323
|Notify-Answer	|HSS	|MME	|NOA	|323
|===

[cols="^0,^0",width="25%"]
|=====================
.2+^.^|weight=2 |en |en
.3+^.^|weight=3 |us |us |us
.2+^.^|weight=2 |hu |hu
.3+|weight=3 |no language |no language |no language
|=====================

[cols="^0,^0",width="25%"]
|==============
|1 |en
|2 |us
|3 |us
|4 |us
|5 |hu
|6 |hu
|7 |no language
|8 |no language
|9 |no language
|10 |en
|11 |en
|12 |us
|13 |us
|==============

[subs="specialchars,quotes"]
----
_<SOF>_
_[red]#Call-ID#_ <unused in the scenario>
[red]#_calledPartyBCDNumber_#: <copied into CAP IDP>
[red]#_callingPartyNumber_#: <copied into CAP IDP>
[red]#_eventTypeBCSM_#: <copied into CAP IDP>
_<EOF>_
----

[options="header",cols="^0,^0,^",width="70%"]
|===============================================================
|Bit |Value |Meaning
|0 |_``0``_ |`IPRoutingAddress` not supported
|0 |_``1``_ |`IPRoutingAddress` supported
|1 |_``0``_ |`VoiceBack` not supported
|1 |_``1``_ |`VoiceBack` supported
|2 |_``0``_ |`VoiceInformation` not supported through speech recognition
|2 |_``1``_ |`VoiceInformation` supported through speech recognition
|3 |_``0``_ |`VoiceInformation` not supported through voice recognition
|3 |_``1``_ |`VoiceInformation` supported through voice recognition
|4 |_``0``_ |Generation of voice announcements from Text not supported
|4 |_``1``_ |Generation of voice announcements from Text supported
|5 |_``-``_ |Reserved
|6 |_``-``_ |Reserved
|7 |_``0``_ |End of standard part
|7 |_``1``_ |This value is reserved in CAP V.2
|===============================================================