= Typographic Conventions
:frame: none
:grid: none

== Inline elements

[grid="rows", frame="none"]
|===
|*Type* |  *Example*
| Messages (Requests, Responses) |  *INVITE* (could be other color)
| Headers |  *_Contact_*
| GUI elements | *[OK]* button, *[Enable]* checkbox
| Parameters | `tsp_GenApp_Diameter_configs`
| Path, file name | _TitanSim-RnXnn-install.tgz_, _/home/username/TitanSim-RnXnn-install_
| Parameter value | _``true``_
|===

_``true``_ +
*_Contact_* +
*INVITE* 

== Parameter descriptions

==== `cps`

++++
<a class="btn btn-primary btn-xs" role="button" data-toggle="collapse" href="#default" aria-expanded="false" aria-controls="collapseExample">
  Default value
</a>

<a class="btn btn-primary btn-xs" role="button" data-toggle="collapse" href="#type" aria-expanded="false" aria-controls="collapseExample">
  Type
</a>

<a class="btn btn-primary btn-xs" role="button" data-toggle="collapse" href="#description" aria-expanded="false" aria-controls="collapseExample">
  Description
</a>
++++

[[type]]
Type: float

[[default]]
Default value: 0.0

[[description]]
Optional parameter. It is the value of calls per second; target call intensity, it must be 0.0 or greater. In case of 0.0, no traffic is generated. The number of calls that can be initiated with the given Traffic Case in one second. To reach and to continuously keep the desired cps value, there must be free entities (that do not participate in any calls) in the given Traffic Case. If there are no free (available) entities, no more calls can be started, at least until a busy entity finishes its call.

++++
<a class="btn btn-primary btn-xs" role="button" data-toggle="collapse" href="#default" aria-expanded="false" aria-controls="collapseExample">
  Default value
</a>

<a class="btn btn-primary btn-xs" role="button" data-toggle="collapse" href="#type" aria-expanded="false" aria-controls="collapseExample">
  Type
</a>

<a class="btn btn-primary btn-xs" role="button" data-toggle="collapse" href="#description" aria-expanded="false" aria-controls="collapseExample">
  Description
</a>
++++

[[type]]
Type: float

[[default]]
Default value: 0.0

[[description]]
Optional parameter. It is the value of calls per second; target call intensity, it must be 0.0 or greater. In case of 0.0, no traffic is generated. The number of calls that can be initiated with the given Traffic Case in one second. To reach and to continuously keep the desired cps value, there must be free entities (that do not participate in any calls) in the given Traffic Case. If there are no free (available) entities, no more calls can be started, at least until a busy entity finishes its call.

== Code example

[source,subs="quotes"]
----
tsp_IMS_Configuration_Scenarios.trafficCases.trafficSpecific.media :=
          {
            enabled := true,
            generator := {
              mlsim :=     
              {
                *#enabled := true,#*
                enableMLSimPlus := true,
----


=== Code example with callouts

[source]
----
tsp_IMS_Configuration_Scenarios.trafficCases.trafficSpecific.media :=
          {
            enabled := true,
            generator := {
              mlsim :=     
              {
                enabled := true,            // <1>
                enableMLSimPlus := true,    // <2>
----
<1> Callout 1
<2> Callout 2

=== User Inputs

  asciidoc -a data-uri -a icons -a toc -a max-width=55em article.txt
  
== Admonitions

++++
{{ book.note }} This is a note {{ book.end }}
++++


++++
{{ book.tip }} This is a tip {{ book.end }}
++++


++++
{{ book.warning }} This is important info {{ book.end }}
++++


++++
{{ book.danger }} This is a warning {{ book.end }}
++++


> **Hint** This is a tip



> **Info** This is a note



> **Caution** This is important info



> **Danger** This is a warning


> ==== Info::Note
> 
> This is a note


> ==== Hint::Tip
> 
> This is a tip


> ==== Warning::Important
> 
> This is important info


> ==== Danger::Warning
> 
> This is a warning


{% hint style='info' %}
 This is a note
{% endhint %}

{% hint style='tip' %}
 This is a tip
{% endhint %}

{% hint style='working' %}
 This is important info
{% endhint %}

{% hint style='danger' %}
 This is a warning
{% endhint %}
