= Typographic Conventions
:frame: none
:grid: none

== Inline elements

[grid="rows", frame="none"]
|===
|*Type* |  *Example*
| Messages (Requests, Responses) |  *[blue]#`INVITE`#* (could be other color)
| Headers |  *`Contact`*
| GUI elements | *[OK]* button, *[Enable]* checkbox
| Parameters | `tsp_GenApp_Diameter_configs`
| Path, file name | _TitanSim-RnXnn-install.tgz_, _/home/username/TitanSim-RnXnn-install_
| Parameter value | _``true``_
|===

_``true``_ +
*`Contact`* +
*[blue]#`INVITE`#* 

== Parameter descriptions

==== `nrOfCalls`

[subs="quotes"]
++++
{{ book.param }}
{{ book.ptype }}
Type: integer
{{ book.paramend }}
{{ book.pdefault }}
Default value: -1
{{ book.paramend }}
{{ book.pdescr }}
The field is used for setting the total number of calls during the execution.

The real number of executed calls can be more than the `nrOfCalls`, but the difference is less than the number of actual `cps` value (for example, if `cps`=3.0, and `nrOfCalls`=10, the calls can be, for example, 12, because every second 3, 3, 3, 1 calls are needed, but 3, 3, 3, 3, cps is scheduled, so it is 12 instead of 10).

After these calls are executed, the application behaves as if the *Stop* button was pressed.

If the parameter is left on default value, the application does not stop the execution based on the number of calls.

This parameter must have the same value as the `nrOfCalls` parameter in `CallTerm` traffic case and cannot be less or equal to `0`.
{{ book.paramend }}
{{ book.end }}
++++


++++
<div class="span6">
  <h4>Attribute Details</h4>
  <ul border="0" class="apiDocs">
    <li class="attribute required" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Unique account identifier in the form of a guid. <br><strong>ONLY</strong> required for updating an existing account<br> <strong>NOT</strong> required when creating a new account.">UID<span class="type">Guid (36)</span></li><li class="description" style="display: list-item;">Unique account identifier in the form of a guid. <br><strong>ONLY</strong> required for updating an existing account<br> <strong>NOT</strong> required when creating a new account.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Name of the account.">Name<span class="type">String (30)</span></li><li class="description">Name of the account.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Account code format includes separator ie 1-1100">DisplayID<span class="type">String (6)</span></li><li class="description">Account code format includes separator ie 1-1100</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="The account classification can be one of the following:<br>
<strong>(1) Asset</strong><br>
<strong>(2) Liability</strong><br> 
<strong>(3) Equity</strong><br> 
<strong>(4) Income</strong><br> 
<strong>(5) CostOfSales</strong><br> 
<strong>(6) Expense</strong><br>
<strong>(8) OtherIncome</strong><br> 
<strong>(9) OtherExpense</strong><br>
">Classification<span class="type">Classification</span></li><li class="description">The account classification can be one of the following:<br>
<strong>(1) Asset</strong><br>
<strong>(2) Liability</strong><br> 
<strong>(3) Equity</strong><br> 
<strong>(4) Income</strong><br> 
<strong>(5) CostOfSales</strong><br> 
<strong>(6) Expense</strong><br>
<strong>(8) OtherIncome</strong><br> 
<strong>(9) OtherExpense</strong><br>
</li><li class="attribute required" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Depending on the classification of the account (e.g. asset), you can define the account's type, see <a href=&quot;http://developer.myob.com/docs/read/Glossary#A&quot;>here</a> for more information on account types.">Type<span class="type">AccountType</span></li><li class="description">Depending on the classification of the account (e.g. asset), you can define the account's type, see <a href="http://developer.myob.com/docs/read/Glossary#A">here</a> for more information on account types.</li><li class="attribute required" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Account number for example 1150. Must be a unique four-digit number that does not include the account type classification number and account separator.">Number<span class="type">Integer (4)</span></li><li class="description">Account number for example 1150. Must be a unique four-digit number that does not include the account type classification number and account separator.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="A description of the account.">Description<span class="type">String (255)</span></li><li class="description">A description of the account.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Pulls through information relating to parent accounts.">ParentAccount</li><li class="description" style="display: list-item;">Pulls through information relating to parent accounts.</li> <li class="subgroupDetails"><ul>
<li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>Foreign Key</strong>: Unique identifier for the parent account in the form of a guid.">UID<span class="type">Guid (36)</span></li><li class="description" style="display: list-item;"><strong>Foreign Key</strong>: Unique identifier for the parent account in the form of a guid.</li><li class="attribute readonly" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Name of the parent account.">Name<span class="type">String (6)</span></li><li class="description" style="display: list-item;">Name of the parent account.</li><li class="attribute readonly" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Parent account code format includes separator ie 1-1000">DisplayID<span class="type">String (6)</span></li><li class="description" style="display: list-item;">Parent account code format includes separator ie 1-1000</li><li class="attribute readonly" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Uniform resource identifier associated with the parent account object.">URI<span class="type">String</span></li><li class="description">Uniform resource identifier associated with the parent account object.</li></ul>
</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>True</strong> indicates the account is active.<br><strong>False</strong> indicates the account is inactive.<br>
<p>A user marks an account as inactive when they no longer need to record transactions to it. An inactive account doesn't appear in selection lists, but it can still be assigned to a transaction, and be included in reports.</p>">IsActive<span class="type">Boolean</span></li><li class="description"><strong>True</strong> indicates the account is active.<br><strong>False</strong> indicates the account is inactive.<br>
<p>A user marks an account as inactive when they no longer need to record transactions to it. An inactive account doesn't appear in selection lists, but it can still be assigned to a transaction, and be included in reports.</p></li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Pulls through information relating to tax codes.">TaxCode</li><li class="description">Pulls through information relating to tax codes.</li><li class="subgroupDetails"><ul>
<li class="attribute required" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>Foreign Key</strong>: Unique guid identifier belonging to the assigned tax code.">UID<span class="type">Guid (36)</span></li><li class="description"><strong>Foreign Key</strong>: Unique guid identifier belonging to the assigned tax code.</li><li class="attribute readonly" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="3 didgit tax code.">Code<span class="type">String (3)</span></li><li class="description">3 didgit tax code.</li><li class="attribute readonly" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Uniform resource identifier associated with the tax code object.">URI<span class="type">String</span></li><li class="description">Uniform resource identifier associated with the tax code object.</li></ul>
</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="The hierarchial level of the account in the Accounts List. Possible values are <strong>1</strong>,&amp;nbsp;<strong>2</strong>,&amp;nbsp;<strong>3</strong>,&amp;nbsp;<strong>4</strong>.&amp;nbsp;The highest level accounts are level 1, the lowest 4. You can only assign levels 2 to 4 to a new account. This is an example showing account hierarchy:
<p><strong>Assets</strong>&amp;nbsp;- Level 1<br><strong>&amp;nbsp; Current Assets</strong>&amp;nbsp;- Level 2<br><strong>&amp;nbsp; &amp;nbsp; Bank Accounts</strong>&amp;nbsp;- Level 3<br>&amp;nbsp; &amp;nbsp; &amp;nbsp; National Bank Account 1 - Level 4<br>&amp;nbsp; &amp;nbsp; &amp;nbsp; National Bank Account 2 - Level 4</p>">Level<span class="type">Integer (4)</span></li><li class="description">The hierarchial level of the account in the Accounts List. Possible values are <strong>1</strong>,&nbsp;<strong>2</strong>,&nbsp;<strong>3</strong>,&nbsp;<strong>4</strong>.&nbsp;The highest level accounts are level 1, the lowest 4. You can only assign levels 2 to 4 to a new account. This is an example showing account hierarchy:
<p><strong>Assets</strong>&nbsp;- Level 1<br><strong>&nbsp; Current Assets</strong>&nbsp;- Level 2<br><strong>&nbsp; &nbsp; Bank Accounts</strong>&nbsp;- Level 3<br>&nbsp; &nbsp; &nbsp; National Bank Account 1 - Level 4<br>&nbsp; &nbsp; &nbsp; National Bank Account 2 - Level 4</p></li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Balance of the account as at the conversion date set for the company file.">OpeningBalance<span class="type">Decimal (13.3)</span></li><li class="description">Balance of the account as at the conversion date set for the company file.</li><li class="attribute readonly" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Current balance of the account. Note that this balance will include all future-dated activity.">CurrentBalance<span class="type">Decimal (13.3)</span></li><li class="description">Current balance of the account. Note that this balance will include all future-dated activity.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Pulls through information relating to banking details.">BankingDetails</li><li class="description">Pulls through information relating to banking details.</li>  <li class="subgroupDetails"><ul>
<li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>ONLY APPLICABLE FOR AU REGION</strong><br>BSB as provided by the financial institution.">BSBNumber<span class="type">String (9)</span></li><li class="description"><strong>ONLY APPLICABLE FOR AU REGION</strong><br>BSB as provided by the financial institution.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Account number as provided by the financial institution.">BankAccountNumber<span class="type">String (20)</span></li><li class="description">Account number as provided by the financial institution.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Bank account name setup.">BankAccountName<span class="type">String (32)</span></li><li class="description">Bank account name setup.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>ONLY APPLICABLE FOR AU REGION</strong><br>Company trading name if applicable for bank account">CompanyTradingName<span class="type">String (50)</span></li><li class="description"><strong>ONLY APPLICABLE FOR AU REGION</strong><br>Company trading name if applicable for bank account</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>ONLY APPLICABLE FOR AU REGION</strong><br>Bank code as provided by the financial institution.">BankCode<span class="type">String (3)</span></li><li class="description"><strong>ONLY APPLICABLE FOR AU REGION</strong><br>Bank code as provided by the financial institution.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>True</strong> indicates the bank account will be used to create bank files (ABA).<br><strong>False</strong> indicates the bank account will not be used to create bank files.">CreateBankFiles<span class="type">Boolean</span></li><li class="description"><strong>True</strong> indicates the bank account will be used to create bank files (ABA).<br><strong>False</strong> indicates the bank account will not be used to create bank files.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>ONLY APPLICABLE FOR AU REGION</strong><br>Direct entry user id as provided by the financial institution.">DirectEntryUserId<span class="type">String (6)</span></li><li class="description"><strong>ONLY APPLICABLE FOR AU REGION</strong><br>Direct entry user id as provided by the financial institution.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>ONLY APPLICABLE FOR AU REGION</strong><br><strong>True</strong> indicates the bank account requires a self balancing transaction.<br><strong>False</strong> indicates the bank account does not require a self balancing transaction.">IncludeSelfBalancingTransaction<span class="type">Boolean</span></li><li class="description"><strong>ONLY APPLICABLE FOR AU REGION</strong><br><strong>True</strong> indicates the bank account requires a self balancing transaction.<br><strong>False</strong> indicates the bank account does not require a self balancing transaction.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Statement particulars assigned to the bank account.">StatementParticulars<span class="type">String (12)</span></li><li class="description">Statement particulars assigned to the bank account.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>ONLY APPLICABLE FOR NZ REGION.</strong><br>Code attached to electronic payment.">StatementCode<span class="type">String</span></li><li class="description"><strong>ONLY APPLICABLE FOR NZ REGION.</strong><br>Code attached to electronic payment.</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>ONLY APPLICABLE FOR NZ REGION.</strong><br>Reference attached to electronic payment.">StatementReference<span class="type">String</span></li><li class="description"><strong>ONLY APPLICABLE FOR NZ REGION.</strong><br>Reference attached to electronic payment.</li></ul>
</li><li class="attribute" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="<strong>True</strong> indicates the account is a header account.Header accounts are used to organise, group and subtotal accounts in the Accounts List and reports.<br><strong>False</strong> indicates the account is a detail account. Only detail accounts can be assigned to transactions.">IsHeader<span class="type">Boolean</span></li><li class="description"><strong>True</strong> indicates the account is a header account.Header accounts are used to organise, group and subtotal accounts in the Accounts List and reports.<br><strong>False</strong> indicates the account is a detail account. Only detail accounts can be assigned to transactions.</li><li class="attribute readonly" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Uniform resource identifier encompasses all types of names and addresses that refer to objects on the web.">URI<span class="type">String</span></li><li class="description">Uniform resource identifier encompasses all types of names and addresses that refer to objects on the web.</li><li class="attribute required" data-toggle="popover" data-placement="bottom" data-trigger="hover" data-original-title="Description" data-content="Number value that changes upon a record update, can be used for change control but does does not preserve a date or a time.<br><strong>ONLY</strong> required for updating an existing account.<br> <strong>NOT</strong> required when creating a new account.">RowVersion<span class="type">String</span></li><li class="description">Number value that changes upon a record update, can be used for change control but does does not preserve a date or a time.<br><strong>ONLY</strong> required for updating an existing account.<br> <strong>NOT</strong> required when creating a new account.</li>
  </ul>
  <p><br><a href="/api/accountright/api-overview/retrieving-data/#PAGING"><strong>Paging:</strong></a> default page size is set to 400 with a maximum of 1000 results.</p>
</div>
++++

== Code example

[subs="quotes",source]
----
tsp_IMS_Configuration_Scenarios.trafficCases.trafficSpecific.media :=
          {
            enabled := true,
            generator := {
              mlsim :=     
              {
                [red]#enabled := true,#
                enableMLSimPlus := true,
----

++++
{{ book.toggle }} This is some text in a collapsible layout. {{ book.end }}{{ book.end }}{{ book.end }}
++++

=== Code example with callouts

[source]
----
tsp_IMS_Configuration_Scenarios.trafficCases.trafficSpecific.media :=
          {
            enabled := true,
            generator := {
              mlsim :=     
              {
                enabled := true,            // <1>
                enableMLSimPlus := true,    // <2>
----
<1> Callout 1
<2> Callout 2

=== User Inputs

  asciidoc -a data-uri -a icons -a toc -a max-width=55em article.txt
  
== Admonitions

++++
{{ book.note }} This is a note {{ book.end }}
++++


++++
{{ book.tip }} This is a tip {{ book.end }}
++++


++++
{{ book.warning }} This is important info {{ book.end }}
++++


++++
{{ book.danger }} This is a warning {{ book.end }}
++++


> **Hint** This is a tip



> **Info** This is a note



> **Caution** This is important info



> **Danger** This is a warning


> ==== Info::Note
> 
> This is a note


> ==== Hint::Tip
> 
> This is a tip


> ==== Warning::Important
> 
> This is important info


> ==== Danger::Warning
> 
> This is a warning

