= Typographic Conventions
:frame: none
:grid: none

== Inline elements

[grid="rows", frame="none"]
|===
|*Type* |  *Example*
| Messages (Requests, Responses) |  *[blue]#`INVITE`#* (could be other color)
| Headers |  *`Contact`*
| GUI elements | *[OK]* button, *[Enable]* checkbox
| Parameters | `tsp_GenApp_Diameter_configs`
| Path, file name | _TitanSim-RnXnn-install.tgz_, _/home/username/TitanSim-RnXnn-install_
| Parameter value | _``true``_
|===

_``true``_ +
*`Contact`* +
*[blue]#`INVITE`#* 

== Parameter descriptions

==== `nrOfCalls`

[subs="quotes"]
++++
{{ book.param }}
{{ book.ptype }}
Type: integer
{{ book.paramend }}
{{ book.pdefault }}
Default value: -1
{{ book.paramend }}
{{ book.pdescr }}
The field is used for setting the total number of calls during the execution.

The real number of executed calls can be more than the `nrOfCalls`, but the difference is less than the number of actual `cps` value (for example, if `cps`=3.0, and `nrOfCalls`=10, the calls can be, for example, 12, because every second 3, 3, 3, 1 calls are needed, but 3, 3, 3, 3, cps is scheduled, so it is 12 instead of 10).

After these calls are executed, the application behaves as if the *Stop* button was pressed.

If the parameter is left on default value, the application does not stop the execution based on the number of calls.

This parameter must have the same value as the `nrOfCalls` parameter in `CallTerm` traffic case and cannot be less or equal to `0`.
{{ book.paramend }}
{{ book.end }}
++++


++++
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Collapsible Group Item #2
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Collapsible Group Item #3
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
</div>
++++

== Code example

[subs="quotes",source]
----
tsp_IMS_Configuration_Scenarios.trafficCases.trafficSpecific.media :=
          {
            enabled := true,
            generator := {
              mlsim :=     
              {
                [red]#enabled := true,#
                enableMLSimPlus := true,
----


++++
{{ book.toggle }} Optional parameter. It defines the number of participants of the call: 2-party or 3-party call can be used. This parameter is the union of the following elements:
{{ book.toggle }} 
callOrig2pty

It is for describing the elements of 2pty calls.
Example
callType := {
          callOrig2pty:={
                    termAnsweringMode := {normal:={}},
                    holdingTimeMin:=5.0,
                    holdingTimeMax:=5.0
          }
}
{{ book.toggle }} 
callOrig2pty

It is for describing the elements of 2pty calls.
Example
callType := {
          callOrig2pty:={
                    termAnsweringMode := {normal:={}},
                    holdingTimeMin:=5.0,
                    holdingTimeMax:=5.0
          }
}

{{ book.end }}
{{ book.end }}
{{ book.end }}
++++

=== Code example with callouts

[source]
----
tsp_IMS_Configuration_Scenarios.trafficCases.trafficSpecific.media :=
          {
            enabled := true,
            generator := {
              mlsim :=     
              {
                enabled := true,            // <1>
                enableMLSimPlus := true,    // <2>
----
<1> Callout 1
<2> Callout 2

=== User Inputs

  asciidoc -a data-uri -a icons -a toc -a max-width=55em article.txt
  
== Admonitions

++++
{{ book.note }} This is a note {{ book.end }}
++++


++++
{{ book.tip }} This is a tip {{ book.end }}
++++


++++
{{ book.warning }} This is important info {{ book.end }}
++++


++++
{{ book.danger }} This is a warning {{ book.end }}
++++


> **Hint** This is a tip



> **Info** This is a note



> **Caution** This is important info



> **Danger** This is a warning


> ==== Info::Note
> 
> This is a note


> ==== Hint::Tip
> 
> This is a tip


> ==== Warning::Important
> 
> This is important info


> ==== Danger::Warning
> 
> This is a warning

