= Typographic Conventions
:frame: none
:grid: none

== Inline elements

[grid="rows", frame="none"]
|===
|*Type* |  *Example*
| Messages (Requests, Responses) |  *[blue]#`INVITE`#* (could be other color)
| Headers |  *`Contact`*
| GUI elements | *[OK]* button, *[Enable]* checkbox
| Parameters | `tsp_GenApp_Diameter_configs`
| Path, file name | _TitanSim-RnXnn-install.tgz_, _/home/username/TitanSim-RnXnn-install_
| Parameter value | _``true``_
|===

_``true``_ +
*`Contact`* +
*[blue]#`INVITE`#* 

== Code example

[subs="quotes",source]
----
tsp_IMS_Configuration_Scenarios.trafficCases.trafficSpecific.media :=
          {
            enabled := true,
            generator := {
              mlsim :=     
              {
                [red]#enabled := true,#
                enableMLSimPlus := true,
----

++++
{{ book.toggle }} This is some text in a collapsible layout. {{ book.end }}{{ book.end }}{{ book.end }}
++++

=== Code example with callouts

[source]
----
tsp_IMS_Configuration_Scenarios.trafficCases.trafficSpecific.media :=
          {
            enabled := true,
            generator := {
              mlsim :=     
              {
                enabled := true,            // <1>
                enableMLSimPlus := true,    // <2>
----
<1> Callout 1
<2> Callout 2

=== User Inputs

  asciidoc -a data-uri -a icons -a toc -a max-width=55em article.txt
  
== Admonitions

++++
{{ book.note }} This is a note {{ book.end }}
++++


++++
{{ book.tip }} This is a tip {{ book.end }}
++++


++++
{{ book.warning }} This is important info {{ book.end }}
++++


++++
{{ book.danger }} This is a warning {{ book.end }}
++++


> **Hint** This is a tip



> **Info** This is a note



> **Caution** This is important info



> **Danger** This is a warning


> ==== Info::Note
> 
> This is a note


> ==== Hint::Tip
> 
> This is a tip


> ==== Warning::Important
> 
> This is important info


> ==== Danger::Warning
> 
> This is a warning

`cps`
++++
{{ book.param }}
{{ book.ptype }}
Type: float
{{ book.paramend }}
{{ book.pdefault }}
Default value: -1
{{ book.paramend }}
{{ book.pdescr }}
The field is used for setting the total number of calls during the execution. The real number of executed calls can be more than the nrOfCalls, but the difference is less than the number of actual cps value (for example, if cps=3.0, and nrOfCalls=10, the calls can be, for example, 12, because every second 3, 3, 3, 1 calls are needed, but 3, 3, 3, 3, cps is scheduled, so it is 12 instead of 10). After these calls are executed, the application behaves as if the Stop button was pressed. If the parameter is left on default value, the application does not stop the execution based on the number of calls. This parameter must have the same value as the nrOfCalls parameter in CallTerm traffic case and cannot be less or equal to 0.
{{ book.paramend }}
{{ book.end }}
++++